apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - buildconfig.yaml
  - imagestream.yaml
  - route.yaml

labels:
  - pairs:
      app: template-ui
      component: ui
    includeSelectors: true
