version: '3.8'

services:
  template-ui:
    build:
      context: .
      dockerfile: Containerfile
    container_name: template-ui-app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - template-ui-network


networks:
  template-ui-network:
    driver: bridge

volumes:
  node_modules:
